@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMUsyQkFGVktBUUs1UllaNUM0WVFNOUg2QyIsIm5hbWUiOiJKb25hdGhhbSBMdXoiLCJpYXQiOjE3NTQ4ODE1NjAsImV4cCI6MTc1NDg4NTE2MH0.FwsepzuiEUxPpGXVb9lAmc--gbzpBvIqwU44TNYwR1c
@cookies = auth-jwt-token={{accessToken}}

### Register account

POST http://localhost:4000/api/accounts/register
Content-Type: application/json

{
  "name": "Jonatham Luz",
  "email": "jonatham.luz@gmail.com",
  "rawPassword": "senha123"
}

### Sign in account

POST http://localhost:4000/api/accounts/sign-in
Content-Type: application/json

{
  "email": "jonatham.luz@gmail.com",
  "rawPassword": "senha123"
}

### Get authenticated account

GET http://localhost:4000/api/accounts/me
Content-Type: application/json
Cookie: {{cookies}}

### Edit account

PUT http://localhost:4000/api/accounts
Content-Type: application/json
Cookie: {{cookies}}

{
  "name": "Jonatham Cordeiro Luz"
}

### Edit account credentials

PUT http://localhost:4000/api/accounts/credentials
Content-Type: application/json
Cookie: {{cookies}}

{
  "currentRawPassword": "senha123",
  "email": "jonatham.luz@gmail.com",
  "newRawPassword": "senha-alterada"
}

### Remove account

DELETE http://localhost:4000/api/accounts
Content-Type: application/json
Cookie: {{cookies}}

{
  "rawPassword": "senha-alterada"
}

### List paginated products from external API

GET http://localhost:4000/api/products?page=1
Content-Type: application/json

### List paginated favorite products by account

GET http://localhost:4000/api/products/favorites?page=1
Content-Type: application/json
Cookie: {{cookies}}

### Favorite product

POST http://localhost:4000/api/products/favorites/1
Content-Type: application/json
Cookie: {{cookies}}

### Unfavorite product

DELETE http://localhost:4000/api/products/favorites/2
Content-Type: application/json
Cookie: {{cookies}}
